srun: error: wn22: task 0: Segmentation fault
srun: error: wn22: task 0: Segmentation fault
srun: error: wn22: task 0: Segmentation fault
srun: error: wn22: task 0: Segmentation fault
srun: error: wn22: task 0: Segmentation fault
srun: error: wn22: task 0: Segmentation fault
srun: error: wn22: task 0: Segmentation fault
srun: error: wn22: task 0: Segmentation fault
srun: error: wn22: task 0: Segmentation fault
srun: error: wn22: task 0: Segmentation fault
srun: error: wn22: task 0: Segmentation fault
srun: error: wn22: task 0: Segmentation fault
srun: error: wn22: task 0: Segmentation fault
srun: error: wn22: task 0: Segmentation fault
srun: error: wn22: task 0: Segmentation fault
srun: error: wn22: task 0: Segmentation fault
srun: error: wn22: task 0: Segmentation fault
srun: error: wn22: task 0: Segmentation fault
srun: error: wn22: task 0: Segmentation fault
srun: error: wn22: task 0: Segmentation fault
srun: error: wn22: task 0: Segmentation fault
srun: error: wn22: task 0: Segmentation fault
srun: error: wn22: task 0: Segmentation fault
srun: error: wn22: task 0: Segmentation fault
srun: error: wn22: task 0: Segmentation fault
